var i18n,lang={};
i18n = lang.sc = {
    tabOnline:'我要咨询',tabLeaveMsg:'我要留言',tabRobot:'自助答疑',tabFreePhone:'免费通话',OK:'确定',guest:'来宾',
    cancel:'取消',sendFile:'传送文件',send:'发送',tip:'提示',fileType:'所支持的文件类型：.txt;.jpg;.rm;.doc;.pdf;.ppt;.xls;.gif;.rar;.zip;.pps',fileSize:'所允许传送的最大文件大小是1MB;',
    visitorAuth:'访客验证', name:'姓名：',phone:'电话：',email:'邮件：',questionType:'咨询类型', hotq:'常见问题',faq:'FAQ',emot:'表情',screen:'截取屏幕',langSel:'界面语言',opinionTip:'服务评价',
    required:'标记（<span class\="required">*</span>）的为必填项目', reason:'请填写差评理由和您的联系方式。',onlyone:'已经有一个客服正在为你服务，如需与另外一个客服对话，请先关闭原来的对话。',
    satisfied:'您是否对此次服务满意？',opinion:'评价：',verygood:'非常满意',good:'满意',normal:'一般',bad:'不满意',verybad:'很差', desc:'描述：',
    invalid:'您的输入信息不符合要求，请填写完整必填选项或者按说明填写',accountInvalid:'该客户账号异常或者已经超过服务日期！',msgFail:'<span class="msgFail">{0}</span>发送失败',
    exitConfirm:'您正在对话中，你确定离开吗？',company:'公司：',dept:'部门：',  msgArrived:'收到新消息',
    connected:'对话已经建立完成，',servicer:'正在与您对话',meetingTitle:'与会人员',queuing:'您正在服务队列中，在您前边有{0}个访客',
    changeNick:'改名', removed:'被移出了会谈',inMeeting:'进入会谈', endChat:'对方结束了对话', transChat:'正在转移对话给',
    transChatFinn:'对话转移完成',toRobot:'当前客服暂时忙碌，将对话托管给了应答系统。',  leaveRobot:'客服取消了托管，回到了当前对话。',
    say:'',download:'点击此处下载',sendImg:'发送了一张图片',fullImg: '点击查看完整图片',whisper:'对{0}说',you:'您',
    disconnected:'目前没有任何客服和你建立连接！', empty:'不能发送空的消息', maxLen:'发送的字数超过了系统的限制', robot:'小语',
    guess:'您是不是咨询下面的问题？',sendFail:'发送消息失败',unknown:'未知错误',cancelFile:'确定取消传送文件么？',sendFinn:'文件上传完毕！',
    fileFail:'文件上传失败！',enter:'Enter发送',ctrlEnter:'Ctrl+Enter发送',save:'保存聊天记录',nick:'昵称：', maxNick:'最长为7个字',
    exist:'昵称已经存在，请选择其他名字',all:'所有', joinMeeting:'您加入到一个会议室中',leave:'离开对话！',
    phoneSuccess:'电话呼叫成功，如果3分钟未收到响应可能是因为对话占线中!',phoneError:'电话呼叫失败，请过会儿再试!',calling:'正在连接服务器...',
    breakingConn:'温馨提示：系统检测到当前网络状况不好，对方有可能收不到您发出的消息',brokenConn:'温馨提示：由于网络状况一直不好，系统已经自动关闭该对话',
    restoreConn:'系统检测到网络已经恢复，对方可以正常收到你发送的消息',quitChat:'结束对话',sendMsg:'发&nbsp;&nbsp;送',
    phoneTitle:'电话回拨',phoneMobile:'手机：',phoneFixed:'固话：',phoneNote:'固话，小灵通，手机来电免费，用户不产生任何费用，非来电免费手机只产生接听费用，无其他额外费用',phoneCall:'免费呼叫',
   needLicence:'感谢您发起呼叫，客服会尽快回拨给您',invalidNumber:'错误的电话号码或者对方未设置电话号码',
    phoneBlocked:'您的电话号码因呼叫频繁被加入到黑名单里',unknownError:'呼叫发生错误',
    phoneCalling:'开始呼叫...',phoneCalled:'呼叫完成，您的电话会接到一个随机号码的呼入请求，请注意接听',
    sendFileStart:'正在发送文件',sendFileFail:'文件发送失败',
    invalidCheckCode:'验证码错误，请检查重新输入',freqCall:'短时间内不能发起更多通话请求，请稍候重试！',
    notOnline:'客服此时恰好离线或者忙碌，您可以 <a href="#" onclick="window.open($.tabUrl(\'leaveMessage\'))">点击此处留言</a>给客服',
    onlineChat:'点击在线咨询',
    robotUseful:'有用',robotUnUsed:'没用'
   };
